# Generated by Django 4.2.5 on 2023-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(null=True, upload_to='resource/'),
        ),
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(null=True, upload_to='type/'),
        ),
    ]
